version: "3.9"
services:
  dbpost:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_lr8
      POSTGRES_USER: usrcompose
      POSTGRES_PASSWORD: passcompose
    volumes:
      - ./init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
