-- Создание таблицы клиентов
CREATE TABLE IF NOT EXISTS Clients (
	"client_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"full_name" VARCHAR(100) NOT NULL,
	"passport_series_number" BIGINT NOT NULL UNIQUE,
	PRIMARY KEY("client_id")
);

CREATE UNIQUE INDEX IF NOT EXISTS client_passport_series_number_idx ON Clients ("passport_series_number");
CREATE INDEX IF NOT EXISTS client_full_name_idx ON Clients ("full_name");

-- Создание таблицы автомобилей
CREATE TABLE IF NOT EXISTS Cars (
	"car_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"model" VARCHAR(50) NOT NULL,
	"color" VARCHAR(50) NOT NULL,
	"year_of_manufacture" SMALLINT NOT NULL,
	"license_plate" VARCHAR(25) NOT NULL UNIQUE,
	"insurance_value" NUMERIC(10, 2) NOT NULL,
	"rental_price_per_day" NUMERIC(8, 2) NOT NULL,
	PRIMARY KEY("car_id")
);

CREATE INDEX IF NOT EXISTS car_model_idx ON Cars ("model");
CREATE UNIQUE INDEX IF NOT EXISTS car_license_plate_idx ON Cars ("license_plate");
CREATE INDEX IF NOT EXISTS car_rental_price_per_day_idx ON Cars ("rental_price_per_day");
CREATE INDEX IF NOT EXISTS car_insurance_value_idx ON Cars ("insurance_value");

-- Создание таблицы аренды
CREATE TABLE IF NOT EXISTS Rental (
	"rental_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"client_id" INTEGER NOT NULL,
	"car_id" INTEGER NOT NULL,
	"start_date" DATE NOT NULL,
	"end_date" DATE NOT NULL,
	"rental_days" INTEGER NOT NULL,
	PRIMARY KEY("rental_id")
);

CREATE INDEX IF NOT EXISTS rental_car_id_idx ON Rental ("car_id");
CREATE INDEX IF NOT EXISTS rental_client_id_idx ON Rental ("client_id");

-- Создание таблицы страховок
CREATE TABLE IF NOT EXISTS Insurance (
	"insurance_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"car_id" INTEGER NOT NULL,
	"insurance_value" NUMERIC(10, 2) NOT NULL,
	"insurance_fee" NUMERIC(8, 2) NOT NULL,
	PRIMARY KEY("insurance_id")
);

CREATE INDEX IF NOT EXISTS insurance_car_id_idx ON Insurance ("car_id");

-- Добавление внешних ключей
ALTER TABLE Rental
ADD FOREIGN KEY("client_id") REFERENCES Clients("client_id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Rental
ADD FOREIGN KEY("car_id") REFERENCES Cars("car_id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Insurance
ADD FOREIGN KEY("car_id") REFERENCES Cars("car_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Вставка тестовых данных
INSERT INTO Clients (full_name, passport_series_number) VALUES
('Короленко Виктор Владимирович', 2009123456),
('Пак Алла Анатольевна', 4510234567),
('Бредихин Алексей Вячеславович', 3121345678);

INSERT INTO Cars (model, color, year_of_manufacture, license_plate, insurance_value, rental_price_per_day) VALUES
('Lada Granta Cross', 'Красный', 2022, 'О153УО68', 1000000, 1800),
('KIA PICANTO 3', 'Серебристый', 2020, 'Р303КТ68', 1350000, 2500),
('Volkswagen Caddy G3 рест', 'Серый', 2011, 'Н575НМ68', 1600000, 2200),
('Volkswagen Tiguan 2 рест R-line', 'Черный', 2021, 'Х283УМ136', 4300000, 7500);

INSERT INTO Rental (client_id, car_id, start_date, end_date, rental_days)
VALUES
(1, 1, CURRENT_DATE - INTERVAL '8 days' , CURRENT_DATE - INTERVAL '2 days', 6),
(2, 2, CURRENT_DATE - INTERVAL '3 day', CURRENT_DATE + INTERVAL '2 days', 5),
(3, 3, CURRENT_DATE - INTERVAL '2 days', CURRENT_DATE + INTERVAL '2 days', 4),
(1, 4, CURRENT_DATE - INTERVAL '1 days', CURRENT_DATE + INTERVAL '4 days', 5);


INSERT INTO Insurance (car_id, insurance_value, insurance_fee) VALUES
(1, 1000000, 100000),
(2, 1350000, 135000),
(3, 1600000, 160000),
(4, 4300000, 430000);
